'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Pulsa.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _20191024_113336() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("20191024_113336", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _588a6507d06f6719692a2d15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("588a6507d06f6719692a2d15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _588a6758d06f6719692a2d22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("588a6758d06f6719692a2d22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property download() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property indosat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("indosat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kisspng_mobile_phones_three_uk_mobile_broadband_internet_paket_internet_murah_desember_2_13_5b7f8f24597d63_5468478615350863723666() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kisspng-mobile-phones-three-uk-mobile-broadband-internet-paket-internet-murah-des"& _ 
                        "ember-2-13-5b7f8f24597d63.5468478615350863723666", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kisspng_telkomsel_telkom_indonesia_mobile_phones_telecommu_telkomsel_5b29a0c70638b7_7785438115294547910255() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kisspng-telkomsel-telkom-indonesia-mobile-phones-telecommu-telkomsel-5b29a0c70638"& _ 
                        "b7.7785438115294547910255", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kisspng_xl_axiata_axiata_group_telecommunications_vector_g_pulsa_xl_rp_1_5b6f69bbc1dd97_9711473415340282197941() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kisspng-xl-axiata-axiata-group-telecommunications-vector-g-pulsa-xl-rp-1-5b6f69bb"& _ 
                        "c1dd97.9711473415340282197941", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PikPng_com_cash_icon_png_1544816() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PikPng.com_cash-icon-png_1544816", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pngfind_com_close_icon_png_904785() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pngfind.com-close-icon-png-904785", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pngfind_com_copyright_png_938050() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pngfind.com-copyright-png-938050", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pngfind_com_logout_button_png_3396821() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pngfind.com-logout-button-png-3396821", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pngguru_com() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pngguru.com", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PngItem_2379025() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PngItem_2379025", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PngItem_23790251() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PngItem_23790251", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pngkey_com_cell_phone_icon_png_11740() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pngkey.com-cell-phone-icon-png-11740", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property uknown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("uknown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
